### ISSUE TITLE
Coral is way too far away from the user to be useful with BoundsControl

### ISSUE THREAD

**Issue by Zee2** [microsoft/MRTK3-iet-tutorials#10]
![image](https://user-images.githubusercontent.com/5544935/184722581-4a719bd6-3bd4-49a4-9f96-c89bac76559a.png)

BoundsControl is intended to be used at near-to-medium distances (with the current sizing/prefab setup). At very far distances like this tutorial (4 meters away) it doesn't work well. Recommendation; move corals much closer to user (and make smaller!)

Normal appearance with smaller objects + closer distances:

![image](https://user-images.githubusercontent.com/5544935/184723199-29cd3ad2-47e3-455f-927c-66c2958d1b19.png)

**Comment by MaxWang-MS** [comment]
We will be doing a tabletop setup.

**Comment by aprilspeight** [comment]
Bounds Control tutorial approach/scenario has been modified. The new objects in the scene are now smaller to accommodate a tabletop setup experience. Handles are fully visible at an appropriate size.
