### ISSUE TITLE
Start the tutorial with non-input-sim mouse-based interaction module

### ISSUE THREAD

**Issue by MaxWang-MS** [microsoft/MRTK3-iet-tutorials#11]
MRTK3 ships with the `CanvasProxyInteractor` which allows users to interact with buttons, bounds controls etc. in the scene without using a simulated hand/controller. I think demonstrating that would be a great starting point. We can order the existing input sim tutorial as the second one in the list. Or we can add this to the existing input sim tutorial.

**Comment by Zee2** [comment]
May want to mention adding the UGUIInputAdapterDraggable to the objects (and in the objmanip tutorial).

**Comment by aprilspeight** [comment]
@Zee2 for clarification, does `CanvasProxyInteractor` need to be added as a component to interactable objects in order to interact w/ a mouse? In addition, what does `UGUIInputAdapaterDraggable` do? Our API reference links are broken at the moment and I'm unable to look it up.

**Comment by aprilspeight** [comment]
Got my answered resolved via Teams :)

**Comment by aprilspeight** [comment]
Created a new module dedicated to previewing scenes that starts w/ mouse-based interactions.
