### ISSUE TITLE
Prioritize the tutorials we ship

### ISSUE THREAD

**Issue by MaxWang-MS** [microsoft/MRTK3-iet-tutorials#13]
Currently there are 7 tutorials we have:
- Input Sim
- Object Manipulator
- Bounds Control
- Button
- Volumetric UI
- Dialog
- Theming

Given Dialog will go through a major refactor soon and theming is still in its early preview stage, I would propose we postpone releasing those two modules. I suggest we add a module that is even more basic than the input sim one (mentioned in #11) as well as add modules for in editor remoting and deploying the app to device.

We don't need to get the remoting and deploying modules ready for the first release, but I hope we do one for #11, whether as its own module or as a part of the input sim module.

**Comment by MaxWang-MS** [comment]
The team decided to include remoting in the first release and move dialog and theming tutorial to a later date.

**Comment by aprilspeight** [comment]
Remoting has been included. Dialog and Theming has been removed/disabled.
