### ISSUE TITLE
Optimize content for AR and VR

### ISSUE THREAD

**Issue by MaxWang-MS** [microsoft/MRTK3-iet-tutorials#15]
Currently the content seems to be designed more for VR than AR (the dome ceiling, the shadow, etc.). We need to make sure the tutorial is deployable to AR and VR devices while achieving a 60fps framerate.

**Comment by aprilspeight** [comment]
Confirmed that this works w/ HL2. I still need to double check for VR. I'll close this after I test on Monday.

**Comment by aprilspeight** [comment]
Tested w/ holographic remoting for HL2 and deployed. Also tested w/ Oculus link. Works fine and posted a video in our chat.
