### ISSUE TITLE
BoundsControl handles aren't supposed to be only enabled through the inspector

### ISSUE THREAD

**Issue by Zee2** [microsoft/MRTK3-iet-tutorials#16]
![image](https://user-images.githubusercontent.com/5544935/185716668-255c802e-94e4-4a8a-8f6c-78e0e8c67ae3.png)

This part of the tutorial seems to imply that the developer has to check the box to enable handles on the BoundsControl. Instead, it's designed so that the user can quickly pinch/click/select/etc the object during runtime and it will enable/disable the handles without any editor tooling.

The checkbox is only meant for developers to be able to control the handles either from some external script or just to specify that the handles should *start* active, rather than needing the pinch action.

**Comment by aprilspeight** [comment]
Modified the approach/scenario for the Bounds Control. This is no longer a step in the tutorial.
