### ISSUE TITLE
Near Z is misconfigured to be wayyyy too large

### ISSUE THREAD

**Issue by Zee2** [microsoft/MRTK3-iet-tutorials#18]
The rig has a scene override on it that sets the near Z to a (way too large) 0.3m. This causes rendering problems.

![image](https://user-images.githubusercontent.com/5544935/185717324-b50d6b69-b391-4638-98cf-7b1d89c6593b.png)

For example, the text on the button is clipped by the nearZ.

![image](https://user-images.githubusercontent.com/5544935/185717199-ec64d73c-50df-4c76-80e7-972459081f0e.png)

**Comment by aprilspeight** [comment]
@Zee2 in a new project that I created, I'm seeing the default value for _Clipping Planes_ is `0.02` and the _Far_ is `100`. Is that correct?

**Comment by Zee2** [comment]
Yeah, that's perfectly fine.

**Comment by aprilspeight** [comment]
Fixed.
