### ISSUE TITLE
Ensure MRGT shaders are used

### ISSUE THREAD

**Issue by MaxWang-MS** [microsoft/MRTK3-iet-tutorials#24]
Make sure we use Graphics Tools/Standard.

**Comment by Zee2** [comment]
And no normal maps please :/

**Comment by aprilspeight** [comment]
I discussed w/ @Zee2 about a month ago that the sea turtle and dolphin both have normal maps. Everything else in the project does not. With the exception of the two aforementioned models, all shaders now reflect MRGT shaders.
