### ISSUE TITLE
None of the example programs work on the quest

### ISSUE THREAD

**Issue by ghost** [microsoft/MRTK3-iet-tutorials#30]
I just want to use the old demo from mixed reality demo but even that is broken. Why was the import examples removed from the Mixed Reality Feature tool in favor of this tutorial for MRTK3?? 

Assets\Scripts\TutorialCallbacks.cs(3,28): error CS0234: The type or namespace name 'Editor' does not exist in the namespace 'Unity.Tutorials.Core' (are you missing an assembly reference?)

**Comment by MaxWang-MS** [comment]
Closing as the user has deleted their account.
