### ISSUE TITLE
Input simulation cover photo on main page is actually MRTK v2

### ISSUE THREAD

**Issue by Zee2** [microsoft/MRTK3-iet-tutorials#5]
The large cover photo for "input simulation" is actually a screenshot of MRTK2.

![image](https://user-images.githubusercontent.com/5544935/182716548-dc1a6b43-558e-4eed-8971-1300091f750c.png)

**Comment by aprilspeight** [comment]
@Zee2 provided and updated image. I replaced the old image w/ the new one.
