### ISSUE TITLE
MRTK3 welcome popup text is outdated/MRTKv2

### ISSUE THREAD

**Issue by Zee2** [microsoft/MRTK3-iet-tutorials#6]
<img width="548" alt="image" src="https://user-images.githubusercontent.com/5544935/184720209-9322984e-7311-4b0b-b007-020b4caa3ceb.png">

We should refer to this as MRTK3, not MRTK-Unity. In addition, OpenVR doesn't exist anymore, Ultraleap is misspelled (but also is not really an XR platform?)

This popup should be updated to be more relevant to MRTK3 and its focus on OpenXR.

**Comment by aprilspeight** [comment]
I change MRTK-Unity to MRTK3 and modified the final sentence of the pop-up to instruct users to first start w/ the **Getting Started** module and not input simulation. I'll leave the remaining updates with @vtieto.

**Comment by aprilspeight** [comment]
All updates for this issue are complete.
