### ISSUE TITLE
Input simulation seems to imply that it's the only way to test your app in the editor

### ISSUE THREAD

**Issue by Zee2** [microsoft/MRTK3-iet-tutorials#7]
![image](https://user-images.githubusercontent.com/5544935/184720687-a55a269d-148c-4572-aa8f-f44deb839f2d.png)

This should probably explain that the preferred way for users to test applications in the editor is by connecting a headset, either PCVR, Link, or Remoting. Simulation is just a backup/fallback!

**Comment by aprilspeight** [comment]
Added a new module on ways to preview a project.
