### ISSUE TITLE
Simulated hands are not a "pattern of cubes shaped to indicate a hand"

### ISSUE THREAD

**Issue by Zee2** [microsoft/MRTK3-iet-tutorials#8]
![image](https://user-images.githubusercontent.com/5544935/184721199-8fa3a2ce-a7e9-46ac-a49f-e68c20495ffe.png)

The cubes seen are actually the hand joints, and they are not unique to input simulation. They are the actual hand joint data that is provided to the interaction system.

Also, the cubes will not be visible in-editor in the next/upcoming MRTK3 release, so this will need to be removed/edited, along with the image.

**Comment by aprilspeight** [comment]
I updated the MRTK3 packages and now have the new hands. I also updated this text.
