### ISSUE TITLE
Input simulation tutorial uses MRTKv2 terminology

### ISSUE THREAD

**Issue by Zee2** [microsoft/MRTK3-iet-tutorials#9]
<img width="473" alt="image" src="https://user-images.githubusercontent.com/5544935/184721500-ce44f10b-dcde-4b06-b02c-b11ae5e9b447.png">

Pointers do not exist in MRTK3. Some terminology:

- **Ray interactor:** the interactor that shoots a ray out into the scene to provide far interaction
- **Reticle:** the visual indicator at the end of the ray
- **Select:** the generic term for the primary action from an interactor used to manipulate an object or click a button

**Comment by aprilspeight** [comment]
Terminology has been updated to reflect MRTK3 changes.
